/** Telling the server when the app broke for somebody.
 *
 * Nothing did this before: a component that threw took the screen blank in a
 * browser nobody on this side owns, and the only way the fault ever reached
 * us was a parent giving up and mentioning it. See src/server/appErrors.ts
 * for what happens to a report, and point 3h of the privacy policy for what
 * is said publicly about it.
 *
 * Two things this file is careful about. It sends no personal data — see
 * scrubErrorText, which is applied to every string before it leaves. And it
 * cannot make a bad situation worse: a broken app often breaks repeatedly, so
 * the same fault is reported once per session, there is a hard cap per
 * session, and a failed report is swallowed rather than thrown. */

import { isAndroidTwa } from './platform';
import { isTelegramMiniApp } from './telegramWebApp';

const REPORT_URL = '/api/error-report';

/** Faults sent per page load. A render loop can throw hundreds of times a
 * second; past a handful nothing new is learned and the only effect is
 * hammering a server the user may also be waiting on. */
const MAX_PER_SESSION = 8;

/** Fingerprints already sent this session, so a fault that repeats on every
 * render is reported once. */
const seen = new Set<string>();
let sent = 0;

/** Removes anything that could identify a person, before the text is sent.
 *
 * The messages this is aimed at are generated by code, not by people, so in
 * practice there is nothing personal in them — but "in practice" is not a
 * guarantee, and an interpolated error message is exactly where a child's
 * name or an email address could end up. The patterns below are the ones
 * worth being sure about:
 *
 * - email addresses, which identify the account directly
 * - bearer tokens and long opaque strings, which are credentials
 * - query strings and URL fragments, which carry ids and referral codes
 * - runs of digits long enough to be an id, a phone number or a card
 *
 * The cost of over-scrubbing is a less specific message; the cost of
 * under-scrubbing is personal data in a log. */
export function scrubErrorText(text: string): string {
  return text
    .replace(/[\w.+-]+@[\w-]+\.[\w.]+/g, '[email]')
    .replace(/\bBearer\s+[\w.\-~+/=]+/gi, 'Bearer [token]')
    .replace(/(\?|#)[^\s)'"]{3,}/g, '$1[params]')
    .replace(/\b[\w-]{32,}\b/g, '[id]')
    .replace(/\b\d{7,}\b/g, '[number]');
}

function platformName(): string {
  if (isTelegramMiniApp) return 'telegram';
  if (isAndroidTwa) return 'twa';
  return 'browser';
}

/** Which build this is, so a fault that is already fixed can be told from one
 * that is still live. Vite replaces this at build time; it is undefined in
 * dev, which is also useful to know. */
function appVersion(): string {
  return import.meta.env.VITE_APP_VERSION ?? (import.meta.env.DEV ? 'dev' : 'unknown');
}

/** The route, without the query string — a referral code or a letter id in
 * there would defeat the point of scrubbing. */
function currentRoute(): string {
  return window.location.pathname;
}

function describe(error: unknown): { message: string; stack: string | null } {
  if (error instanceof Error) {
    return {
      message: scrubErrorText(`${error.name}: ${error.message}`),
      stack: error.stack ? scrubErrorText(error.stack) : null,
    };
  }
  // A thrown string, a rejected object, an ErrorEvent with nothing useful on
  // it — still worth hearing about, so say what little there is rather than
  // dropping it.
  try {
    return { message: scrubErrorText(`Non-Error thrown: ${String(error)}`.slice(0, 300)), stack: null };
  } catch {
    return { message: 'Non-Error thrown, not stringifiable', stack: null };
  }
}

/** Reports a fault. Safe to call from anywhere, including a catch block that
 * is already handling a failure — it never throws and never awaits anything
 * the caller needs. */
export function reportAppError(error: unknown, context?: string): void {
  try {
    const { message, stack } = describe(error);
    const full = context ? `${context}: ${message}` : message;

    const key = `${full}|${(stack ?? '').slice(0, 120)}`;
    if (seen.has(key) || sent >= MAX_PER_SESSION) return;
    seen.add(key);
    sent++;

    void fetch(REPORT_URL, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        message: full,
        stack,
        route: currentRoute(),
        lang: localStorage.getItem('brifo_lang'),
        platform: platformName(),
        appVersion: appVersion(),
      }),
      // The page may be unloading — a crash often is the last thing that
      // happens — so let the browser finish this after navigation.
      keepalive: true,
    }).catch(() => {
      // Offline, blocked, or the route itself is down. Nothing to do: this is
      // the diagnostic channel, not the feature.
    });
  } catch {
    // Reporting a fault must never be the thing that throws.
  }
}

/** Catches what no component caught. Call once, as early as possible. */
export function installErrorReporting(): void {
  window.addEventListener('error', (event) => {
    // A failed <img>/<script> load also fires this, with no error attached —
    // noise, not a fault worth a report.
    if (!event.error && !event.message) return;
    reportAppError(event.error ?? event.message, 'window.onerror');
  });

  window.addEventListener('unhandledrejection', (event) => {
    reportAppError(event.reason, 'unhandledrejection');
  });
}
